import { Sparkles } from "lucide-react";
import { cn } from "@/lib/utils";

/** Consistent marker for anything AI-generated (violet accent + sparkle). */
export function AiBadge({
  label = "Generated by AI",
  className,
}: {
  label?: string;
  className?: string;
}) {
  return (
    <span
      className={cn(
        "inline-flex items-center gap-1 text-[11px] font-medium text-ai-muted-foreground",
        className,
      )}
    >
      <Sparkles size={11} />
      {label}
    </span>
  );
}
