// AUTO-GENERATED by scripts/gen-tenant-models.ts — do not edit by hand.
// Refresh with `pnpm gen:tenant-models` (runs as part of `pnpm db:generate`).
// Lists every model declaring an `organisationId` field; the tenancy guard in
// lib/infra/tenancy.ts consumes this so the set can never drift from the schema.

export const TENANT_SCOPED_MODELS: ReadonlySet<string> = new Set(["Channel","ChannelEvent","Contact","Conversation","Integration","Invitation","Member","Message","MessageAttachment","MessageTemplate"]);
