import { readFileSync, writeFileSync } from "node:fs";
import { resolve } from "node:path";
import { parseTenantScopedModels } from "../lib/infra/parse-tenant-models";

/**
 * Generates lib/infra/tenant-models.generated.ts from the Prisma schema so the
 * tenancy guard's model set always matches the schema. Run via
 * `pnpm gen:tenant-models` (also chained into `pnpm db:generate`).
 */
const root = process.cwd();
const schemaPath = resolve(root, "prisma/schema.prisma");
const outPath = resolve(root, "lib/infra/tenant-models.generated.ts");

const schema = readFileSync(schemaPath, "utf8");
const models = parseTenantScopedModels(schema);

const content = `// AUTO-GENERATED by scripts/gen-tenant-models.ts — do not edit by hand.
// Refresh with \`pnpm gen:tenant-models\` (runs as part of \`pnpm db:generate\`).
// Lists every model declaring an \`organisationId\` field; the tenancy guard in
// lib/infra/tenancy.ts consumes this so the set can never drift from the schema.

export const TENANT_SCOPED_MODELS: ReadonlySet<string> = new Set(${JSON.stringify(
  models,
)});
`;

writeFileSync(outPath, content);
console.log(
  `[gen-tenant-models] wrote ${models.length} model(s): ${
    models.join(", ") || "(none)"
  }`,
);
